version: '3.8'

services:
  db_phuonghai:
    image: "postgres:13"
    ports:
      - "5436:5436"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=phuonghai_admin
      - POSTGRES_PASSWORD=0799888358
      - POSTGRES_DB=phuonghaiTest
  db_kishop:
    image: "postgres:13"
    ports:
      - "5434:5434"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kishop_admin
      - POSTGRES_PASSWORD=0799888358
      - POSTGRES_DB=kishop
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2282:2282"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2282
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/data
      - ./zk-single-kafka-single/zoo1/datalog:/datalog
  kafka_kishop:
    image: confluentinc/cp-kafka:5.5.3
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-103.82.25.243}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2282"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
  redis:
    image: redis
    ports:
      - "6179:6179"